### ISSUE TITLE
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tseemann** [kdmurray91/SRApy#1]
Install seemed ok, but dynamic library link error at runtime. Ideas?

```
pip2 install srapy
Collecting srapy
  Downloading srapy-0.1.15-py2-none-any.whl
Requirement already satisfied: six<2.0,>=1.9 in ./.linuxbrew/lib/python2.7/site-packages (from srapy)
Requirement already satisfied: biopython>=1.65 in ./.linuxbrew/lib/python2.7/site-packages (from srapy)
Requirement already satisfied: docopt<0.7,>=0.6 in ./.linuxbrew/lib/python2.7/site-packages/docopt-0.6.2-py2.7.egg (from srapy)
Collecting progressbar2<2.8,>=2.7 (from srapy)
  Downloading progressbar2-2.7.3.tar.gz
Collecting lxml<3.5,>=3.4 (from srapy)
  Downloading lxml-3.4.4.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 393kB/s
Building wheels for collected packages: progressbar2, lxml
  Running setup.py bdist_wheel for progressbar2 ... done
  Stored in directory: /home/linuxbrew/.cache/pip/wheels/1b/73/4b/d98799dae259a37df54e524dfeaf10bfaed30ac0a7f93a7767
  Running setup.py bdist_wheel for lxml ... done
  Stored in directory: /home/linuxbrew/.cache/pip/wheels/ab/61/f2/413c1a5cd899ec8d50e38f0f6196c99d7ae56f094d0575e8bf
Successfully built progressbar2 lxml
Installing collected packages: progressbar2, lxml, srapy
Successfully installed lxml-3.4.4 progressbar2-2.7.3 srapy-0.1.15
```

```
$ get-run.py
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/get-run.py", line 8, in <module>
    import srapy
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/srapy/__init__.py", line 3, in <module>
    from lxml import etree
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory

**Comment by kdmurray91** [comment]
Hi Torsten,

Well that is a new one. Seems lxml is compiled from source fine. I'm assuming this is linux (given linuxbrew paths), which distro/version? Do you have *both* libxslt-dev and libxml-dev installed? (precise package names differ by distro/version).

The other thing to check would be `ldd /path/to/site-packages/lxml/etree.so`, where lxml/etree.so is the compiled python module.

Cheers,
K

**Comment by bzd111** [comment]
I hava the same question, How to solve it ? Help

**Comment by kdmurray91** [comment]
Hi @bzd111 

The only explanation I can think of for this happening is that `libxslt.so.1` is removed by some system update. The only solution I can think of is to force-uninstall the `lxml` python package with something like `pip uninstall lxml`, then reinstall it with `pip install -U lxml`, which will re-build the python extension using whatever the operating system's current libxslt library is.

**Comment by scottstanfield** [comment]
I had this problem when I was SSH'd into the linux box using `ssh -Y` which forwards X11 to the client. Without `-Y` I didn't get the error above. I think the `libxslt.so.1` was loading via PyQt5, which is the QT UI kit, which obviously wasn't happy.

**Comment by WangBing521595** [comment]
v啊打发

**Comment by WangBing521595** [comment]
1、find / -name libxslt.so.1  wheather exist or not    if not ,yum  install
2、add the path of supervisor  on /root/.bash_profile
3、supervisor start

**Comment by pegom96** [comment]
I had a similar problem on raspbian, this solved it: https://stackoverflow.com/questions/24689016/libxml2-importerror-when-importing-etree-from-lxml

**sudo apt-get install libxslt-dev**

**Comment by kdmurray91** [comment]
Hi Pedro,

yes, libxslt will need to be installed for lxml. I'm unsure how the lxml library gets installed at all without these. Perhaps the lxml binary wheels on pypi are broken on some systems? Or perhaps they require specific versioned .so files that don't exist everywhere?

Anyway, I'm going to close this issue. As far as I can tell, this is an issue with lxml, rather than srapy, but feel free to re-open this issue if anyone has further issues.

Cheers,
Kevin

**Comment by fuomag9** [comment]
On raspbian `libxslt-dev` is missing by default for example and it was not installed when I installed lxml via pip.

**Comment by RonnieWang2018** [comment]
How about SUSE 12 SP1. I have the same issue when run "SUSEConnect -s"  This VM is hosting in Azure. 
I found this error after performing security patching and rebooting.
![image](https://user-images.githubusercontent.com/42931997/102196853-b9655180-3ec0-11eb-9e0b-f0a984ee6473.png)

**Comment by kdmurray91** [comment]
If you installed lxml from source, uninstall and reinstall it. If you installed if from suse's package repos, then do the equivalent of apt update && apt upgrade. If it is still broken after that, report the bug to suse. Nothing in this has anything to do with SRApy itself.

Best,
KDM

**Comment by newtoid** [comment]
Might be worth pointing out that a default/full install of raspbian includes this but the Lite version does not. I have a cluster for load tests and a pair of them running Lite both had this same issue while Full did not :-)
