### ISSUE TITLE
Seems like the path to python executable is user specific

### ISSUE THREAD

**Issue by elhb** [kdmurray91/SRApy#2]
Seems like the adress to python executable is user specific

Installed in virtual enviroment on OSX using the pip install command as follows:
```
mkdir analysis_automation
cd analysis_automation
virtualenv --python=python2.7 analysis_automation_venv
source analysis_automation_venv/bin/activate
pip install --upgrade pip
pip install srapy
get-project-sras.py -p 376266
```

Gives the following error:
-bash: /Users/erikborgstrom/analysis_automation/analysis_automation_venv/bin/get-project-sras.py: /home/kevin/.virtualenvs/sra/bin/python: bad interpreter: No such file or directory

**Comment by kdmurray91** [comment]
Wow, how did I manage that! Whoops. I've hopefully pushed a new package that won't have the hard-coded paths
